/**
 * config.demo.js — Monitor de Compliance Empresarial
 * ====================================================
 * DATOS 100% FICTICIOS para demo a prospects.
 * Se carga automáticamente cuando la URL contiene ?demo=true
 * NUNCA exponer config.js real en una demo. Usar siempre este archivo.
 */

const CONFIG = {

  empresa: {
    nombre:       "Constructora del Sur S.A.",
    cuit:         "30-99887766-5",
    sector:       { es: "Construcción y obra pública", en: "Construction and public works", pt: "Construção e obras públicas" },
    tamanio:      { es: "grande", en: "large", pt: "grande" },
    pais:         "Argentina",
    provincias:   ["CABA", "Mendoza", "Tucumán"],
    internacional: true,
    logo:         "",
    color_primario: "#1a3a5c",
    responsable_compliance: "Dr. Carlos Medina",
    contacto:     "compliance@constructoradelsur.com.ar",
  },

  programa_integridad: {
    nivel_madurez:   "medio",
    fecha_inicio:    "2024-01-15",
    ultima_revision: "2025-11-01",
    registrado_rite: true,
    url_rite:        "https://www.rite.gob.ar/empresas",

    elementos_obligatorios: [
      { id: "codigo_etica",
        label:    { es: "Código de ética / conducta", en: "Code of ethics / conduct", pt: "Código de ética / conduta" },
        estado:   "completo",
        evidencia:{ es: "Aprobado por Directorio 01/2024", en: "Approved by the Board 01/2024", pt: "Aprovado pela Diretoria 01/2024" } },
      { id: "reglas_licitacion",
        label:    { es: "Reglas para contrataciones públicas y licitaciones", en: "Rules for public procurement and tenders", pt: "Regras para contratações públicas e licitações" },
        estado:   "completo",
        evidencia:{ es: "Procedimiento LP-007 vigente", en: "Procedure LP-007 in effect", pt: "Procedimento LP-007 vigente" } },
      { id: "capacitacion",
        label:    { es: "Capacitaciones periódicas a directores y empleados", en: "Periodic training for directors and employees", pt: "Treinamentos periódicos para diretores e funcionários" },
        estado:   "en_progreso",
        evidencia:{ es: "3 de 6 módulos completados", en: "3 of 6 modules completed", pt: "3 de 6 módulos concluídos" } },
    ],

    elementos_opcionales: [
      { id: "analisis_riesgos",
        label:    { es: "Análisis periódico de riesgos", en: "Periodic risk analysis", pt: "Análise periódica de riscos" },
        estado:   "completo",
        evidencia:{ es: "Matriz actualizada 11/2025", en: "Matrix updated 11/2025", pt: "Matriz atualizada 11/2025" } },
      { id: "canal_denuncias",
        label:    { es: "Canal de denuncias confidencial", en: "Confidential whistleblowing channel", pt: "Canal de denúncias confidencial" },
        estado:   "completo",
        evidencia:{ es: "Canal activo en compliance@constructoradelsur.com.ar", en: "Channel active", pt: "Canal ativo" } },
      { id: "due_diligence",
        label:    { es: "Due diligence de terceros", en: "Third-party due diligence", pt: "Due diligence de terceiros" },
        estado:   "en_progreso",
        evidencia:{ es: "Protocolo DD-002 en implementación", en: "Protocol DD-002 being implemented", pt: "Protocolo DD-002 em implementação" } },
      { id: "politica_regalos",
        label:    { es: "Política de regalos e invitaciones", en: "Gifts and invitations policy", pt: "Política de presentes e convites" },
        estado:   "completo",
        evidencia:{ es: "Política GR-001 distribuida", en: "Policy GR-001 distributed", pt: "Política GR-001 distribuída" } },
      { id: "responsable",
        label:    { es: "Responsable interno de Compliance designado", en: "Internal Compliance Officer appointed", pt: "Responsável interno de Compliance designado" },
        estado:   "completo",
        evidencia:{ es: "Dr. C. Medina — Res. Directorio 01/2024", en: "Dr. C. Medina — Board Resolution 01/2024", pt: "Dr. C. Medina — Res. Diretoria 01/2024" } },
      { id: "politica_ddjj",
        label:    { es: "Política de declaraciones juradas de conflictos", en: "Conflict of interest disclosure policy", pt: "Política de declarações de conflitos de interesse" },
        estado:   "pendiente",
        evidencia:{ es: "", en: "", pt: "" } },
      { id: "investigaciones",
        label:    { es: "Procedimiento de investigaciones internas", en: "Internal investigations procedure", pt: "Procedimento de investigações internas" },
        estado:   "en_progreso",
        evidencia:{ es: "Borrador aprobado, pendiente implementación", en: "Draft approved, pending implementation", pt: "Rascunho aprovado, implementação pendente" } },
      { id: "plan_comunicacion",
        label:    { es: "Plan de comunicación interna del Programa", en: "Program internal communication plan", pt: "Plano de comunicação interna do Programa" },
        estado:   "pendiente",
        evidencia:{ es: "", en: "", pt: "" } },
    ],
  },

  mapa_riesgo: [
    { area: { es: "Comercial / Ventas", en: "Sales / Commercial", pt: "Comercial / Vendas" },
      riesgo: "alto", probabilidad: 4, impacto: 5,
      descripcion: { es: "Interacción frecuente con sector público. Riesgo de cohecho en licitaciones.", en: "Frequent interaction with the public sector. Risk of bribery in tenders.", pt: "Interação frequente com o setor público. Risco de suborno em licitações." } },
    { area: { es: "Compras y Abastecimiento", en: "Procurement and Supply", pt: "Compras e Abastecimento" },
      riesgo: "alto", probabilidad: 4, impacto: 4,
      descripcion: { es: "Terceros no evaluados. Riesgo de lavado por cadena de proveedores.", en: "Unvetted third parties. Money laundering risk through the supply chain.", pt: "Terceiros não avaliados. Risco de lavagem por meio da cadeia de fornecedores." } },
    { area: { es: "Finanzas y Contabilidad", en: "Finance and Accounting", pt: "Finanças e Contabilidade" },
      riesgo: "medio", probabilidad: 3, impacto: 4,
      descripcion: { es: "Registros contables. Riesgo de balances falsos (art. 300 bis CP).", en: "Accounting records. Risk of falsified financial statements.", pt: "Registros contábeis. Risco de balanços falsos." } },
    { area: { es: "Recursos Humanos", en: "Human Resources", pt: "Recursos Humanos" },
      riesgo: "medio", probabilidad: 2, impacto: 3,
      descripcion: { es: "Contratación de ex funcionarios públicos. Conflictos de interés.", en: "Hiring of former public officials. Conflicts of interest.", pt: "Contratação de ex-funcionários públicos. Conflitos de interesse." } },
    { area: { es: "Gobierno Corporativo", en: "Corporate Governance", pt: "Governança Corporativa" },
      riesgo: "alto", probabilidad: 3, impacto: 5,
      descripcion: { es: "Toma de decisiones. Riesgo de negociaciones incompatibles (art. 265 CP).", en: "Decision making. Risk of incompatible negotiations.", pt: "Tomada de decisões. Risco de negociações incompatíveis." } },
    { area: { es: "Operaciones / Producción", en: "Operations / Production", pt: "Operações / Produção" },
      riesgo: "bajo", probabilidad: 2, impacto: 2,
      descripcion: { es: "Bajo nivel de interacción con funcionarios públicos.", en: "Low level of interaction with public officials.", pt: "Baixo nível de interação com funcionários públicos." } },
    { area: { es: "Tecnología e Información", en: "Technology and Information", pt: "Tecnologia e Informação" },
      riesgo: "bajo", probabilidad: 2, impacto: 3,
      descripcion: { es: "Acceso a datos sensibles. Riesgo de uso indebido de información.", en: "Access to sensitive data. Risk of misuse of information.", pt: "Acesso a dados sensíveis. Risco de uso indevido de informações." } },
    { area: { es: "Relaciones Institucionales", en: "Institutional Relations", pt: "Relações Institucionais" },
      riesgo: "alto", probabilidad: 3, impacto: 5,
      descripcion: { es: "Lobby, donaciones, patrocinios. Riesgo de tráfico de influencias.", en: "Lobbying, donations, sponsorships. Influence peddling risk.", pt: "Lobby, doações, patrocínios. Risco de tráfico de influência." } },
  ],

  capacitaciones: [
    { modulo: { es: "Introducción a la Ley 27.401", en: "Introduction to Law 27.401", pt: "Introdução à Lei 27.401" },
      obligatorio: true, completado: 91, fecha_limite: "2026-03-31",
      destinatarios: { es: "Todos", en: "All", pt: "Todos" } },
    { modulo: { es: "Código de Ética y Conducta", en: "Code of Ethics and Conduct", pt: "Código de Ética e Conduta" },
      obligatorio: true, completado: 85, fecha_limite: "2026-03-31",
      destinatarios: { es: "Todos", en: "All", pt: "Todos" } },
    { modulo: { es: "Procedimientos en Contrataciones Públicas", en: "Public Procurement Procedures", pt: "Procedimentos em Contratações Públicas" },
      obligatorio: true, completado: 68, fecha_limite: "2026-06-30",
      destinatarios: { es: "Comercial, Compras", en: "Sales, Procurement", pt: "Comercial, Compras" } },
    { modulo: { es: "Due Diligence de Terceros", en: "Third-Party Due Diligence", pt: "Due Diligence de Terceiros" },
      obligatorio: false, completado: 42, fecha_limite: "2026-09-30",
      destinatarios: { es: "Compras, Finanzas", en: "Procurement, Finance", pt: "Compras, Finanças" } },
    { modulo: { es: "Prevención de Lavado de Activos (UIF)", en: "Anti-Money Laundering (AML)", pt: "Prevenção à Lavagem de Dinheiro" },
      obligatorio: true, completado: 55, fecha_limite: "2026-07-31",
      destinatarios: { es: "Finanzas, Directores", en: "Finance, Directors", pt: "Finanças, Diretores" } },
    { modulo: { es: "FCPA y Normativa Internacional", en: "FCPA and International Regulations", pt: "FCPA e Normativa Internacional" },
      obligatorio: false, completado: 25, fecha_limite: "2026-12-31",
      destinatarios: { es: "Directores, Comercial", en: "Directors, Sales", pt: "Diretores, Comercial" } },
  ],

  cuits_verificados: [
    { razon_social: "Materiales del Norte S.R.L.", cuit: "30-55544433-2", fecha: "2025-10-05", resultado: "sin_antecedentes", area_vinculada: "Compras y Abastecimiento" },
    { razon_social: "Transporte Andino S.A.",      cuit: "30-66677788-9", fecha: "2025-09-18", resultado: "sin_antecedentes", area_vinculada: "Operaciones / Producción" },
    { razon_social: "Servicios Globales Ltda.",    cuit: "30-44455566-7", fecha: "2025-08-22", resultado: "alerta_ocde",     area_vinculada: "Compras y Abastecimiento" },
    { razon_social: "Ingeniería Patagónica S.A.",  cuit: "30-33322211-4", fecha: "2025-07-30", resultado: "sin_antecedentes", area_vinculada: "Comercial / Ventas" },
  ],

  historial_score: [
    { mes: "Ene 2026", score: 38 },
    { mes: "Feb 2026", score: 44 },
    { mes: "Mar 2026", score: 49 },
    { mes: "Abr 2026", score: 55 },
    { mes: "May 2026", score: 61 },
    { mes: "Jun 2026", score: 64 },
  ],

  plan_mejora: [
    { accion: { es: "Completar módulo UIF — Prevención de Lavado", en: "Complete AML module", pt: "Concluir módulo de Lavagem de Dinheiro" },
      prioridad: "alta",
      responsable: { es: "RRHH", en: "HR", pt: "RH" },
      vence: "2026-07-31", estado: "en_progreso" },
    { accion: { es: "Implementar política de DDJJ conflictos interés", en: "Implement conflict of interest disclosure policy", pt: "Implementar política de declarações de conflito de interesse" },
      prioridad: "alta",
      responsable: { es: "Compliance", en: "Compliance", pt: "Compliance" },
      vence: "2026-08-15", estado: "pendiente" },
    { accion: { es: "Evaluar 6 proveedores pendientes de due diligence", en: "Assess 6 vendors pending due diligence", pt: "Avaliar 6 fornecedores pendentes de due diligence" },
      prioridad: "media",
      responsable: { es: "Compras", en: "Procurement", pt: "Compras" },
      vence: "2026-09-30", estado: "pendiente" },
    { accion: { es: "Finalizar procedimiento investigaciones internas", en: "Finalize internal investigations procedure", pt: "Finalizar procedimento de investigações internas" },
      prioridad: "media",
      responsable: { es: "Legal", en: "Legal", pt: "Jurídico" },
      vence: "2026-10-31", estado: "en_progreso" },
    { accion: { es: "Desarrollar plan de comunicación interna del programa", en: "Develop program internal communication plan", pt: "Desenvolver plano de comunicação interna do programa" },
      prioridad: "baja",
      responsable: { es: "Compliance", en: "Compliance", pt: "Compliance" },
      vence: "2026-12-31", estado: "pendiente" },
  ],

  exposicion_internacional: {
    opera_en_usa:    false,
    opera_en_uk:     false,
    opera_en_brasil: true,
    opera_en_ue:     false,
    leyes_aplicables: ["Convención OCDE (Ley 25.319)", "UNCAC (Ley 26.097)", "Lei Anticorrupção Brasil 12.846/2013"],
  },

  meaci_url: "https://meaci-production.up.railway.app",
  meaci_api: "https://meaci-production.up.railway.app/api/cruce-compr",

  predictor: {
    pesos: { programa: 25, capacitacion: 20, due_diligence: 20, riesgo: 15, comunicacion: 10, investigacion: 10 },
    valores_actuales: {
      programa:      64,
      capacitacion:  61,
      due_diligence: 55,
      riesgo:        100,
      comunicacion:  20,
      investigacion: 25,
    },
    escenarios_base: [
      { nombre: "Situación actual", valores: { programa: 64, capacitacion: 61, due_diligence: 55, riesgo: 100, comunicacion: 20, investigacion: 25 } },
      { nombre: "Meta 6 meses",     valores: { programa: 82, capacitacion: 78, due_diligence: 72, riesgo: 100, comunicacion: 60, investigacion: 55 } },
      { nombre: "Nivel mínimo OA",  valores: { programa: 60, capacitacion: 60, due_diligence: 40, riesgo: 60,  comunicacion: 40, investigacion: 40 } },
    ],
  },

  benchmark: {
    score_propio: null,
    sector_default: "construccion",
    sectores: {
      construccion:  { nombre: "Construcción / Obra pública", p25: 38, p50: 52, p75: 68, top10: 84 },
      servicios:     { nombre: "Servicios profesionales",     p25: 45, p50: 60, p75: 74, top10: 89 },
      industria:     { nombre: "Industria manufacturera",     p25: 40, p50: 55, p75: 70, top10: 85 },
      energia:       { nombre: "Energía y recursos naturales",p25: 50, p50: 65, p75: 78, top10: 92 },
      finanzas:      { nombre: "Servicios financieros",       p25: 55, p50: 70, p75: 82, top10: 94 },
      tecnologia:    { nombre: "Tecnología",                  p25: 48, p50: 63, p75: 76, top10: 91 },
      salud:         { nombre: "Salud y farmacéutico",        p25: 52, p50: 66, p75: 79, top10: 93 },
      comercio:      { nombre: "Comercio y retail",           p25: 35, p50: 48, p75: 62, top10: 78 },
    },
  },
};
